-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin_users
(
    admin_id serial NOT NULL,
    email text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.articles
(
    id serial NOT NULL,
    title text COLLATE pg_catalog."default",
    source text COLLATE pg_catalog."default",
    date date,
    description text COLLATE pg_catalog."default",
    link text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.artists
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default",
    contact text COLLATE pg_catalog."default",
    CONSTRAINT artists_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.members
(
    id serial NOT NULL,
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    role text COLLATE pg_catalog."default",
    photo_file_name text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    fun_fact text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    CONSTRAINT members_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.past_events
(
    id serial NOT NULL,
    past_flyer_file_name text COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    subtitle text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    place text COLLATE pg_catalog."default",
    CONSTRAINT past_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.past_events_artists
(
    past_event_id integer NOT NULL,
    artist_id integer NOT NULL,
    CONSTRAINT past_shows_artists_pkey PRIMARY KEY (past_event_id, artist_id)
);

CREATE TABLE IF NOT EXISTS public.reset_tokens
(
    admin_user_id integer,
    token text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone,
    CONSTRAINT reset_tokens_pkey PRIMARY KEY (token)
);

CREATE TABLE IF NOT EXISTS public.upcoming_events
(
    id serial NOT NULL,
    title text COLLATE pg_catalog."default",
    subtitle text COLLATE pg_catalog."default",
    url text COLLATE pg_catalog."default",
    flyer_url text COLLATE pg_catalog."default",
    CONSTRAINT upcoming_events_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.past_events_artists
    ADD CONSTRAINT past_events_artists_artist_id_fkey FOREIGN KEY (artist_id)
    REFERENCES public.artists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.past_events_artists
    ADD CONSTRAINT past_events_artists_past_event_id_fkey FOREIGN KEY (past_event_id)
    REFERENCES public.past_events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;